go_import_path: github.com/behance/go-chronos
language: go
sudo: false
before_install:
  - go get github.com/Masterminds/glide
  - go get github.com/onsi/ginkgo/ginkgo
  - go get github.com/golang/lint/golint
  - glide install
script:
  - make test
